### ISSUE TITLE
Button "rodar" does not work.

### ISSUE THREAD

**Issue by LucassAquino** [LucasBonato/Pokedex-StudyAPI#1]
When I click, "rodar" does not upload the container with the new Pokemon.

My suggestion: 
Change api url when you click.

Code: 

  let numComponent = document.querySelector("#newPokeID");
  let num = numComponent.value;

  fetch(url + num + "/")

**Comment by LucasBonato** [comment]
Thanks for the JavaScript I was struggling to solve it, I already added it to the code
